use schooldb;
show tables;

-- WRITE A STORED PROCEDURE TO PRINT WELCOME MESSAGE
delimiter //
create procedure showMSG()
begin
select "WELCOME" as 'MSG';
end //

-- drop procedure showMSG; -- use drop procedure whrn if any changes made then drop and run above block once ahain and then call.
call showMSG;

-- WRITE A PROCEDURE TO SHOW ALL EMPLOYEE DETAILS.
DELIMITER $$
CREATE PROCEDURE SHOWALLemp()
BEGIN 
SELECT * FROM EMP;
END $$
CALL SHOWALLemp;

-- USE OF PROCEDURE PARAMETERS (IN,OUT,INOUT)
-- USE OF 'IN 'PARAMETER (ALLOWS TO TAKE INPUT FROM USER)

-- WRITE A PORCEDURE TO SHOW ENTERED EMP NAME DETAILS
DELIMITER #
CREATE PROCEDURE showgivenEMPDETAILS (IN EMPNAME CHAR(20))
BEGIN
SELECT * FROM EMP WHERE ENAME=EMPNAME;
END #
CALL showgivenEMPDETAILS('SOOJA');
CALL showgivenEMPDETAILS('LAURA MARTINEZ');
CALL showgivenEMPDETAILS('EMILY DAVIS');
 OR 

DELIMITER #
CREATE PROCEDURE showgivenEMPDETAILS1 (IN EMPNAME CHAR(20))
BEGIN
SELECT * FROM EMP WHERE ENAME=EMPNAME OR ENAME LIKE %ENAME%;
END #

call showgivenempdetails1('Emily'); -- SHOWS ERROR

DROP PROCEDURE showgivenEMPDETAILS1;

-- WRITW A PROCEDURE TO SHOW CALCULATOR OPERATION
DELIMITER $
CREATE PROCEDURE calci(IN A INT, IN B INT, OUT ADDn INT, OUT SUB INT, OUT MULT INT, OUT DIVn INT)
BEGIN
SET ADDn=A+B;
SET SUB=A-B;
SET MULT=A*B;O 
SET DIVn=A/B;
END $
DROP procedurE calci;
CALL calci(5,6,@ADDn,@SUB,@MULT,@DIVn);
SELECT @ADDn,@SUB,@MULT,@DIVn;

-- OUT PARAMETER
-- WRITE A PROCEDURE TO SHOW EMPLOYEES SALARY WHOSE IS ID ENTERED BY USER BY USING IN AND OUT PARAMETER.

DELIMITER //
CREATE PROCEDURE showempsalary(IN EMPID INT, OUT SAL INT)
BEGIN
SELECT SALARY FROM EMP WHERE EID=EMPID;
END //

CALL showempsalAry(6,@SAL);
CALL SHOWALLEMP;
CALL showempsalary(9,@sal);

-- INOUT PARAMETER 
-- WRITE A PROCEDURE TO SHOW COUNT OF EMP AS PER GENDER SPECIFIED IN INPUT.
DELIMITER //
CREATE PROCEDURE countEMP(INOUT INGENDER CHAR(20))
BEGIN
SELECT COUNT(GENDER) FROM EMP WHERE GENDER=INGENDER;
END //
DROP PROCEDURE COUNTEMP;
SET @INGENDER='FEMALE';


-- IF BLOCK WHICH IS CONDITIONAL STATEMENT.
-- WRITE PROCEDURE TO CHECK NUMBER IS ZERO OR NOT
DELIMITER $$
CREATE PROCEDURE chkno(IN N INT)
BEGIN
IF N=0 THEN
SELECT 'N IS ZERO' AS ANS; -- TRUE BLOCK
ELSE 
SELECT 'N IS NOT ZERO' AS ANS; -- FALSE BLOCK
END IF;
END $$
CALL chkno(0);
CALL CHKNO(6.9);