use hr;
-- Q.1 CREATE A STORED PROCEDURE WITH NAME AS GET_EMPLOYEE THAT RETURN THE LIST OF EMPLOYEE WITH THEIR
-- FISRT_NAME, LAST_NAME, EMAIL, DEPARTMENT NAME OF ALL EMPLOYEES.

DELIMITER $
CREATE PROCEDURE GET_EMPLOYEE()
BEGIN
SELECT  E.FIRST_NAME, E.LAST_NAME, E.EMAIL, D.DEPARTMENT_NAME
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;
END $

DROP PROCEDURE GET_EMPLOYEE;

CALL GET_EMPLOYEE();

-- Q.2 With respect to employee table and department table in the last assignment, 
-- Create Stored Procedure with the name  GetLimitedEmployee with the input parameter.
-- Procedure display the list of employee with their first_name, last_name, salary, hire_date. 
-- Input parameter must be a integer which is used to display limited number of records.

DELIMITER #
CREATE PROCEDURE GetLimitedEmployee(IN COUNT INT)
BEGIN
SELECT FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES LIMIT COUNT;
END # 
CALL GetLimitedEmployee(2);
CALL GetLimitedEmployee(20);


-- Q.3 With respect to the table employee and department created, Create a stored procedure named as CountEmployee that returns
-- the count of total number of employee in employee Table.
DELIMITER //
CREATE PROCEDURE CountEmployee(OUT TOTALCOUNT INT)
BEGIN
SELECT COUNT(EMPLOYEE_ID) INTO TOTALCOUNT FROM EMPLOYEES;
END //

SET @TOTALCOUNT=0;
CALL CountEmployee(@TOTALCOUNT);
SELECT @TOTALCOUNT AS TOTALEMPLOYEE; 
SELECT @TOTALCOUNT-6 AS TOTALEMPLOYEE;

-- LADDER IF/ELSE IN PROCEDURES.
DELIMITER //
CREATE PROCEDURE SHOWGRADE(IN PER FLOAT)
BEGIN
IF PER>=80 AND PER<=100 THEN
SELECT 'O GRADE' AS GRADE;
ELSE IF PER>=60 AND PER<80 THEN
SELECT 'A GRADE' AS GRADE;
ELSE IF PER>=40 AND PER<60 THEN
SELECT 'B GRADE' AS GRADE;
ELSE IF PER>=0 AND PER<40 THEN
SELECT 'FAIL' AS GRADE;
ELSE 
select 'INVALID PERCENTAGE' AS GRADE;
END IF;
END IF;
END IF;
END IF;
END //
DROP PROCEDURE SHOWGRADE;
CALL SHOWGRADE(100);
CALL SHOWGRADE(-70);

-- WRITE A PROCDURE TP SHOW SALARY GRADES FOR EVERY EMPLOYEES AS PER GIVEN BELOW.
-- 1)GRADE I-SALARY>=50000 AND SALARY<=100000
-- 2)GRADE II-SALARY>=20000 AND SALARY<=50000
-- 3)GRADE III-SALARY>=5000 AND SALARY<=20000
-- 4)SHOW VERY LOW FOR SALARY>=0 AND SALARY<=5000
-- OTHER THAN THIS SHOW N/A

DELIMITER //
CREATE PROCEDURE SALARYGRADES()
BEGIN
SELECT EMPLOYEE_ID,FIRST_NAME, SALARY FROM EMPLOYEES;
IF SALARY>=50000 AND SALARY<100000 THEN
SELECT 'GRADE I' AS GRADE;
ELSE IF SALARY>=20000 AND SALARY<50000 THEN
SELECT 'GRADE II' AS GRADE;
ELSE IF SALARY>=5000 AND SALARY<20000 THEN
SELECT 'GRADE III' AS GRADE;
ELSE IF SAALRY>=0 AND SALARY<5000 THEN
SELECT 'VERY LOW' AS GRADE;
ELSE 
SELECT 'N/A' AS GRADE;
END IF;
END IF;
END IF;
END IF;
END // 

CALL SALARYGRADES; -- INCORRECT ANS BECAUSE IT IS NOT ITERATING WE HAVE TO USE LOOP.

-- LOOPING 1)WHILE LOOP 2) REPEAT LOOP 3) LABEL LOOP
-- PARAMETER IN LOOP(START,CONDITION,INCREMENT/DECREMENT)

DELIMITER //
CREATE PROCEDURE WHILEDEMO()
BEGIN
DECLARE i INT DEFAULT 1;
DECLARE OUTPUT VARCHAR(20) DEFAULT '';
WHILE i<=5 DO -- SELECT i;
SET OUTPUT=CONCAT(OUTPUT,i,' ');
SET i=i+1;
END WHILE;
SELECT OUTPUT;
END //
CALL WHILEDEMO();

DROP PROCEDURE WHILEDEMO;

-- REPEAT OR UNTI LOOP
DELIMITER #
CREATE PROCEDURE REPEATLOOP()
BEGIN
DECLARE i INT;
DECLARE OUTPUT VARCHAR (20);
SET i=1;
SET OUTPUT='';
REPEAT SET OUTPUT=CONCAT(OUTPUT,I,' ');
SET i=i+1;
UNTIL i>5 END REPEAT;
SELECT OUTPUT;
END #
CALL REPEATLOOP;

-- LABEL LOOP
DELIMITER //
CREATE PROCEDURE LABELOOP()
BEGIN
DECLARE i INT DEFAULT 1;
DECLARE OUTPUT VARCHAR(20) DEFAULT '';
GO:LOOP
IF i>5 THEN LEAVE GO;
END IF;
SET OUTPUT=CONCAT(OUTPUT,i,' ');
SET i=i+1;
ITERATE GO;
END LOOP;
SELECT OUTPUT;
END //

CALL LABELOOP;
